spring:
  profiles:
    active: test
  application:
    name: auth-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      enabled: true
      locator:
        lower-case-service-id: true
      routes:
        - id: auth_third_party_route
          uri: lb://auth-third-party
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
## 启动端口，和限制访问端口
server:
  port: 9600
  #address: 127.0.0.1
  tomcat:
    uri-encoding: UTF-8